#!/bin/bash
# One-time developer setup: builds a self-contained BoxPilot.app and installs
# it into /Applications on the client's Mac.
#
# Run this ONCE, from a clone of this repository, on the machine that will
# run BoxPilot:
#
#   bash packaging/mac/install.sh
#
# Re-running it later (e.g. to ship an update) is also safe: it backs up the
# database, stops the previous install's containers, then rebuilds and
# restarts in place — it never touches the .env it already generated, so
# secrets and the client's data both survive an update.
#
# After this, the client only ever double-clicks BoxPilot in /Applications
# (or a Dock shortcut to it). They never need Terminal, npm, Docker, Prisma
# or PostgreSQL directly.
#
# All persistent, non-reinstallable state (real secrets, the compose file
# actually used at runtime, backups, logs, the installed version) lives in
# ~/Library/Application Support/BoxPilot/ — never inside
# /Applications/BoxPilot.app, which install.sh freely deletes and recreates
# on every run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TEMPLATE_APP="$SCRIPT_DIR/BoxPilot.app"
TARGET_APP="/Applications/BoxPilot.app"
PROJECT_DEST="$TARGET_APP/Contents/Resources/project"

SUPPORT_DIR="$HOME/Library/Application Support/BoxPilot"
SUPPORT_ENV="$SUPPORT_DIR/.env"
SUPPORT_COMPOSE="$SUPPORT_DIR/docker-compose.yml"
SUPPORT_COMPOSE_PROD="$SUPPORT_DIR/docker-compose.prod.yml"
BACKUPS_DIR="$SUPPORT_DIR/backups"
LOGS_DIR="$SUPPORT_DIR/logs"
VERSION_FILE="$SUPPORT_DIR/version.txt"

# docker-compose.prod.yml (merged on top of the base file) removes
# PostgreSQL's host port entirely and binds the app to 127.0.0.1 only, so a
# client's Mac never exposes either service to the rest of the network.
compose() {
  docker compose --env-file "$SUPPORT_ENV" -f "$SUPPORT_COMPOSE" -f "$SUPPORT_COMPOSE_PROD" --project-directory "$PROJECT_DEST" "$@"
}

echo "==> BoxPilot installer"
echo "    Repository: $REPO_ROOT"
echo "    Config/data: $SUPPORT_DIR"

# 1. Docker Desktop must be installed by hand first; we don't try to install it.
if [ ! -d "/Applications/Docker.app" ] && ! command -v docker >/dev/null 2>&1; then
  echo "!! Docker Desktop is not installed on this Mac."
  echo "   Install it from https://www.docker.com/products/docker-desktop/ and run this script again."
  exit 1
fi

# Docker.app being present isn't enough: the `docker` CLI is only symlinked
# into PATH the first time Docker Desktop is actually opened. Installed-but-
# never-launched is the most common cause of "docker: command not found"
# right after a fresh install.
if ! command -v docker >/dev/null 2>&1; then
  echo "!! Docker Desktop est installé mais la commande 'docker' est introuvable."
  echo "   Ouvrez l'application Docker Desktop une première fois (icône baleine),"
  echo "   attendez qu'elle soit prête, puis relancez ce script dans un NOUVEAU"
  echo "   terminal."
  exit 1
fi

echo "==> Making sure Docker Desktop is running"
if ! docker info >/dev/null 2>&1; then
  open -a Docker
  echo "    Waiting for Docker Desktop to start..."
  WAITED=0
  until docker info >/dev/null 2>&1; do
    sleep 2
    WAITED=$((WAITED + 2))
    if [ "$WAITED" -ge 90 ]; then
      echo "!! Docker Desktop met trop de temps à démarrer. Ouvrez-le manuellement,"
      echo "   attendez que l'icône baleine soit stable, puis relancez ce script."
      exit 1
    fi
  done
fi

mkdir -p "$SUPPORT_DIR" "$BACKUPS_DIR" "$LOGS_DIR"

# 2. Generate a real, private production .env ONCE. Never overwritten on
#    later runs, so re-installing/updating never rotates secrets or breaks
#    the client's existing session cookies. Every value here is generated
#    freshly for this install — nothing here ever matches what's committed
#    in .env.example.
if [ ! -f "$SUPPORT_ENV" ]; then
  echo "==> Generating $SUPPORT_ENV (first install)"
  SESSION_SECRET="$(openssl rand -hex 32)"          # 32 bytes, cryptographically random
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
  DEMO_ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | cut -c1-16)"

  cat > "$SUPPORT_ENV" <<EOF
# Generated by packaging/mac/install.sh on $(date '+%Y-%m-%d %H:%M:%S').
# This file holds real production secrets for this install. It is NOT part
# of the git repository and must never be committed or copied into
# /Applications/BoxPilot.app.
SESSION_SECRET="$SESSION_SECRET"
POSTGRES_USER="boxpilot"
POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
POSTGRES_DB="boxpilot"
APP_URL="http://localhost:3000"
DEMO_ADMIN_EMAIL="admin@boxpilot.local"
DEMO_ADMIN_PASSWORD="$DEMO_ADMIN_PASSWORD"
EOF
  chmod 600 "$SUPPORT_ENV"

  echo ""
  echo "   Admin login for this install:"
  echo "     E-mail:        admin@boxpilot.local"
  echo "     Mot de passe:  $DEMO_ADMIN_PASSWORD"
  echo "   (also readable later in $SUPPORT_ENV)"
  echo ""
else
  echo "==> Reusing existing $SUPPORT_ENV (secrets and admin password unchanged)"
fi

# 3. If a previous install is running, back up the database before touching
#    anything, then stop it. This update MUST NOT proceed if the backup
#    fails — an update is exactly the moment a bad build could corrupt data,
#    so skipping straight to "continue anyway" here would defeat the point.
if [ -f "$SUPPORT_COMPOSE" ] && compose ps --status running --services 2>/dev/null | grep -q '^db$'; then
  echo "==> Backing up the database before updating"
  if ! BOXPILOT_PROJECT_DIR="$PROJECT_DEST" bash "$REPO_ROOT/scripts/backup-production.sh"; then
    echo "!! Backup failed. Aborting the update — the previous install has NOT been touched." >&2
    exit 1
  fi
fi

if [ -f "$SUPPORT_COMPOSE" ]; then
  echo "==> Stopping the previous BoxPilot install"
  compose down || true
fi

# 4. Install the template (icon, launcher, Info.plist) and a clean copy of
#    the project source at their final location. The app bundle itself is
#    fully disposable: it holds no secrets and no data, only code — it gets
#    wiped and recreated on every run.
echo "==> Installing BoxPilot.app to $TARGET_APP"
rm -rf "$TARGET_APP"
cp -R "$TEMPLATE_APP" "$TARGET_APP"
mkdir -p "$PROJECT_DEST"

rsync -a \
  --exclude ".git" \
  --exclude ".env" \
  --exclude "node_modules" \
  --exclude ".next" \
  --exclude "coverage" \
  --exclude "playwright-report" \
  --exclude "test-results" \
  --exclude "packaging" \
  "$REPO_ROOT/" "$PROJECT_DEST/"

# 5. Neither compose file carries secrets (only variable references), so
#    refreshing them from the repo on every install/update is safe and lets
#    compose-level fixes ship normally.
cp "$PROJECT_DEST/docker-compose.yml" "$SUPPORT_COMPOSE"
cp "$PROJECT_DEST/docker-compose.prod.yml" "$SUPPORT_COMPOSE_PROD"

# 6. Build the Docker images now so the client's first click is fast, and do
#    a full startup so migrations run and demo data seeds before handover.
echo "==> Building Docker images (this can take a few minutes the first time)"
compose build

echo "==> Starting BoxPilot to run migrations and seed data"
compose up -d

echo "==> Waiting for http://localhost:3000 to answer"
for _ in $(seq 1 60); do
  if curl -sf -o /dev/null "http://localhost:3000"; then
    break
  fi
  sleep 2
done

if ! curl -sf -o /dev/null "http://localhost:3000"; then
  echo "!! BoxPilot did not come up in time. Check the logs with:"
  echo "     docker compose --env-file \"$SUPPORT_ENV\" -f \"$SUPPORT_COMPOSE\" -f \"$SUPPORT_COMPOSE_PROD\" --project-directory \"$PROJECT_DEST\" logs"
  exit 1
fi

# 7. Track what's installed. `app_version` is the single source of truth
#    (package.json, also returned by GET /api/health) — the git hash is
#    just extra traceability for support and falls back gracefully outside
#    of a git checkout.
{
  echo "app_version=$(node -p "require('$REPO_ROOT/package.json').version" 2>/dev/null || echo unknown)"
  echo "installed_at=$(date '+%Y-%m-%d %H:%M:%S')"
  echo "source_commit=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
} > "$VERSION_FILE"

echo ""
echo "✅ BoxPilot is installed and running."
echo "   The client can now open /Applications/BoxPilot.app (or drag it to the Dock)."
echo "   Config, secrets, backups and logs: $SUPPORT_DIR"
